# Run the site on your local machine (have Ruby and Middleman installed)
watch:
	bundle exec jekyll serve --watch

# Compile the site on your local machine
build:
	bundle install

# Troubleshooting try to update
update:
	bundle update

flush:
	source ~/.rvm/scripts/rvm